name: Validate

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          repository: 'https://github.com/MassHesteria/beat.git'

      - name: make
        run: cd beat && make

