name: Validate

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          repository: 'MassHesteria/beat'

      - name: Install GTK2
        run: apt update && apt install -y libgtk2.0-dev libgtksourceview2.0-dev libx11-dev

      - name: make
        run: cd beat && make

