name: Validate

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          repository: 'MassHesteria/beat'
          path: 'beat-cpp'

      - name: Install GTK2
        run: |
          sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu/ focal universe"
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-dev libgtksourceview2.0-dev libx11-dev

      - name: make
        run: |
          touch a.txt
          cd beat-cpp/beat
          mkdir -p obj
          mkdir -p out
          sed -i '/#pragma once/a #include <stdexcept>' ../hiro/hiro.hpp
          sed -i '/#pragma once/a #include <stdexcept>' ../nall/platform.hpp
          sed -i '1s/^/#include <stdexcept>\n/' beat.hpp
          make

      - name: beat.cpp - patch
        run: |
          beat-cpp/beat/out/beat -create:bps cpp_patch.bps a.txt beat-cpp/beat/beat.cpp
          beat-cpp/beat/out/beat -apply:bps cpp_patch.bps a.txt patched.cpp
          diff beat-cpp/beat/beat.cpp patched.cpp
          rm patched.cpp
          bun run beat.ts -create:bps ts_patch.bps a.txt beat-cpp/beat/beat.cpp
          diff cpp_patch.bps ts_patch.bps && echo 'beat.cpp patch passed'

      - name: beat.png - patch
        run: |
          beat-cpp/beat/out/beat -create:bps cpp_patch.bps beat-cpp/beat/resource/beat.ico beat-cpp/beat/resource/beat.png
          beat-cpp/beat/out/beat -apply:bps cpp_patch.bps beat-cpp/beat/resource/beat.ico patched.png
          diff beat-cpp/beat/resource/beat.png patched.png
          rm patched.png
          bun run beat.ts -create:bps ts_patch.bps beat-cpp/beat/resource/beat.ico beat-cpp/beat/resource/beat.png
          diff cpp_patch.bps ts_patch.bps && echo 'beat.png patch passed'

      - name: beat.cpp beat.png - failure
        continue-on-error: true
        run: |
          beat-cpp/beat/out/beat -create:bps cpp_patch.bps beat-cpp/beat/resource/beat.ico beat-cpp/beat/resource/beat.png
          beat-cpp/beat/out/beat -apply:bps cpp_patch.bps beat-cpp/beat/resource/beat.ico patched.png
          diff beat-cpp/beat/resource/beat.png patched.png
          rm patched.png
          bun run beat.ts -create:bps ts_patch.bps beat-cpp/beat/beat.cpp beat-cpp/beat/resource/beat.png
          diff cpp_patch.bps ts_patch.bps

